#!/bin/sh

### Rewind commit/author timestamps of N commits back to a
### specified offset compared to current values of each commit
### (C) 2019-2022 by Jim Klimov

set -xv
[ -n "$BACK" ] || BACK=2
PREV=1
# For BSD could be OFFSET="-v-3d -v-9H'
[ -n "$OFFSET" ] || OFFSET="- 3 days"
INITLOG="`git log -1`"

[ -n "$GSED" ] || {
    # For expression below, sed should not claim
    #     bad flag in substitute command: '}'
    (command -v gsed) && GSED=gsed || GSED=sed
}
[ -n "$GDATE" ] || {
    # Should support "date -d ..."
    (command -v gdate) && GDATE=gdate || GDATE=date
    # Not covered here yet as a method (just a fallback below),
    # but programs for BSD would use multi-token syntax like:
    #   date -f '%Y-%m-%d %H:%M:%S %z' -j -v '-3d' -v '-9H' "$DOLD"
}

# Note that we must rewrite history starting from the newest
# commit, tracking back to the oldest, otherwise the edited
# timestamps tend to end up broken (reset to "today + offset").
while [ "$PREV" -le "$BACK" ] ; do
	GIT_EDITOR="$GSED -e '/^pick /{s/^pick /edit /;:p' -e 'n;bp' -e '}' " git rebase -i HEAD~${PREV} && \
	while sleep 0.1 ; do
		echo "===== START COMMIT PARSE:"
		DOLD="`git show -s --format='%ci'`"
		DNEW="`$GDATE -d "$DOLD $OFFSET"`" && [ -n "$DNEW" ] \
		|| { DNEW="`$GDATE -f '%Y-%m-%d %H:%M:%S %z' $OFFSET -j "$DOLD"`" && [ -n "$DNEW" ] ; } \
		|| { echo "FATAL: No compatible 'date' program was found for the OFFSET value (and other args) used" >&2 ; exit 1 ; }

		echo "=== AMENDING:"
		echo "=== OLD DATE: $DOLD"
		echo "=== NEW DATE: $DNEW"
		GIT_COMMITTER_DATE="$DNEW" GIT_AUTHOR_DATE="$DNEW" git commit --amend --no-edit --date "$DNEW"

		echo "=== RESULT LOG:"
		git log -1

		echo "=== CONTINUE REBASE:"
		git rebase --continue || break

		git status | grep rebasing || { echo "+++ DONE" && break ; }

		echo "===== Next loop..."
		echo ""
	done
	PREV="`expr $PREV + 1`"
	echo "+++++++++++++++ NEXT CYCLE"
done

echo ""
echo ""
echo "==============================================================================="
echo "DONE; if you want to 'git reset' to initial state, this was the starting point:"
echo "$INITLOG"
echo "==============================================================================="
